apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
  labels:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/instance: hydra
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: hydra
      app.kubernetes.io/instance: hydra
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hydra
        app.kubernetes.io/instance: hydra
      annotations:
        checksum/hydra-config: 5f99b551670581d60a0adc6e7313cb670b6add08fe4791efb517970dadc1b5b5
        checksum/hydra-secrets: d392f2f4f1aa87335ac96492479624c487fc4d164a90fd9adb439e343c17b14a
    spec:
      volumes:
        - name: hydra-config-volume
          configMap:
            name: hydra
      serviceAccountName: hydra
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 60
      containers:
        - name: hydra
          image: {{ kustom.image }}
          imagePullPolicy: IfNotPresent
          command:
            - hydra
          args:
            - serve
            - all
            - --config
            - /etc/config/hydra.yaml
          volumeMounts:
            - name: hydra-config-volume
              mountPath: /etc/config
              readOnly: true
          ports:
            - name: http-public
              containerPort: 4444
              protocol: TCP
            - name: http-admin
              containerPort: 4445
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health/alive
              port: 4445
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health/ready
              port: 4445
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
            failureThreshold: 5
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 2
          env:
            - name: URLS_SELF_ISSUER
              value: https://my-lb.adm13/hydra
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: hydra
                  key: dsn
            - name: SECRETS_SYSTEM
              valueFrom:
                secretKeyRef:
                  name: hydra
                  key: secretsSystem
            - name: SECRETS_COOKIE
              valueFrom:
                secretKeyRef:
                  name: hydra
                  key: secretsCookie
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seLinuxOptions:
              level: s0:c123,c456
            seccompProfile:
              type: RuntimeDefault
          lifecycle: {}
      initContainers: null
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
